title: Title
url: https://www.slssandbox.com
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#0b233f"
  secondary-color: "#2b63d9"
  media-colors:
    - title: media-color-one
      color: "#e96a6a"
    - title: media-color-two
      color: "#4ecbd3"
    - title: media-color-three
      color: "#fbbc04"
    - title: media-color-four
      color: "#af75d2"
    - title: media-color-five
      color: "#73c235"
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d3vprc9xc2bvz5.amplifyapp.com
prod: https://master.d3vprc9xc2bvz5.amplifyapp.com
facebook-pixel: ""
shareicon: /images/isomer-logo.svg
is_government: false
google_analytics: ""
google_analytics_ga4: ""
linkedin-insights: ""
